#!/bin/bash

component=$(basename $0)
base_dir=$(dirname $0)/../..
source $base_dir/cluster/scripts/functions.sh

if [ $# -lt 2 ]; then
  print_component_usage $component
  exit 1
fi

command=$1
number=$2
name=${component}${number}

case "$command" in
  create)
    case "$3" in
      simple|ha|"")
        cluster_config=${3:-simple}
        
        echo "Creating $name"

        # EXPOSED PORTS
        #
        # 16000 - the port the hmaster should bind to => hbase.master.port
        # 16010 - hmaster http ui => hbase.master.info.port
        #
        # 1st node gets default ports, 2nd node gets default ports + 1 and so on

        port_inc=$number
        let "port_inc -= 1"

        hmaster_port=16000
        let "hmaster_port += $port_inc"
        hmaster_webui_port=16010
        let "hmaster_webui_port += $port_inc"

        docker run -dit \
          --name $name \
          --hostname $name.cluster \
          --network=cluster \
          --expose $hmaster_port -p $hmaster_port:$hmaster_port \
          --expose $hmaster_webui_port -p $hmaster_webui_port:$hmaster_webui_port \
          --mount source=$name-data,target=/data \
          --mount type=bind,source=$base_dir/software/hbase/share,target=/share \
          --mount type=bind,source=$base_dir/software/hadoop/share,target=/hadoop-share \
          -m 512M --memory-swap 512M \
          -e "HBASE_MASTER_OPTS=-Xmx410m" \
          -e "CLUSTER_CONFIG=$cluster_config" \
          --ulimit nofile=10000:10000 \
          hbase:${HBASE_VER}_${HADOOP_VER} bash /share/start-hmaster.sh

        addContainerToHostsFile $name
        ;;
      *)
        print_component_usage $component
        exit 1
        ;;
    esac
    ;;
  start)
    echo "Starting $name"
    docker container start $name
    ;;
  stop)
    echo "Stopping $name"
    docker container kill $name
    ;;
  delete)
    echo "Deleting $name"
    docker container rm $name
    removeLineContaining $name.cluster /etc/hosts
    docker volume rm $name-data
    ;;
  *)
    print_component_usage $component
    exit 1
esac