#!/bin/bash

component=$(basename $0)
base_dir=$(dirname $0)/../..
source $base_dir/cluster/scripts/functions.sh

if [ $# -lt 1 ]; then
  print_component_usage $component false
  exit 1
fi

command=$1
name=${component}

case "$command" in
  create)
    case "$2" in
      simple|ha|"")
        cluster_config=${2:-simple}
        
        echo "Creating $name"

        # EXPOSED PORTS
        #
        # 10020 - mapredhistoryserver ipc port => mapreduce.jobhistory.address
        # 19888 - mapredhistoryserver http ui => mapreduce.jobhistory.webapp.address

        base_dir=$(dirname $0)/../..

        docker run -dit \
          --name $name \
          --hostname $name.cluster \
          --network=cluster \
          --expose 10020 -p 10020:10020 \
          --expose 19888 -p 19888:19888 \
          --mount source=$name-data,target=/data \
          --mount type=bind,source=$base_dir/software/hadoop/share,target=/share \
          -m 512M --memory-swap 512M \
          -e "HADOOP_JOB_HISTORYSERVER_HEAPSIZE=410" \
          -e "CLUSTER_CONFIG=$cluster_config" \
          hadoop:$HADOOP_VER bash /share/start-mapredhistoryserver.sh

        addContainerToHostsFile $name
        ;;
      *)
        print_component_usage $component false
        exit 1
        ;;
    esac
    ;;
  start)
    echo "Starting $name"
    docker container start $name
    ;;
  stop)
    echo "Stopping $name"
    docker container kill $name
    ;;
  delete)
    echo "Deleting $name"
    docker container rm $name
    removeLineContaining $name.cluster /etc/hosts
    docker volume rm $name-data
    ;;
  *)
    print_component_usage $component false
    exit 1
esac