#!/bin/bash

component=$(basename $0)

function print_usage() {
  echo
  echo "Usage: $component COMMAND"
  echo 
  echo "Available commands:"
  echo 
  echo "  create"
  echo "  start"
  echo "  stop"
  echo "  delete"
}

if [ $# -ne 1 ]; then
  print_usage
  exit 1
fi

base_dir=$(dirname $0)/../..
command=$1
name=${component}

case "$command" in
  create)
    echo "Creating $name"

    # EXPOSED PORTS
    #
    # 10020 - mapredhistoryserver ipc port => mapreduce.jobhistory.address
    # 19888 - mapredhistoryserver http ui => mapreduce.jobhistory.webapp.address

    base_dir=$(dirname $0)/../..

    docker run -dit \
      --name $name \
      --hostname $name.cluster \
      --network=cluster \
      --expose 10020 -p 10020:10020 \
      --expose 19888 -p 19888:19888 \
      --mount source=$name-data,target=/data \
      --mount type=bind,source=$base_dir/software/hadoop/share,target=/share \
      hadoop:$HADOOP_VER /share/start-mapredhistoryserver.sh

    ip=$(docker inspect \
      --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' \
      $name)
      
     sudo sh -c "echo $ip $name.cluster >> /etc/hosts"
  ;;
  start)
    echo "Starting $name"
    docker container start $name
  ;;
  stop)
    echo "Stopping $name"
    docker container kill $name
  ;;
  delete)
    echo "Deleting $name"
    docker container rm $name
    sudo sh -c "sed -i \"/$name.cluster/d\" /etc/hosts"
    docker volume rm $name-data
  ;;
  *)
    print_usage
    exit 1
esac