#!/bin/bash

component=$(basename $0)

function print_usage() {
  echo
  echo "Usage: $component COMMAND NUMBER"
  echo 
  echo "Available commands:"
  echo 
  echo "  create"
  echo "  start"
  echo "  stop"
  echo "  delete"
}

if [ $# -ne 2 ]; then
  print_usage
  exit 1
fi

base_dir=$(dirname $0)/../..
command=$1
number=$2
name=${component}${number}

case "$command" in
  create)
    echo "Creating $name"

    prefix=$number
    let "prefix -= 1"

    if [ "$prefix" -eq "0" ]; then
      prefix=""
    fi
   
    docker run -dit \
      --name $name \
      --network=container:datanode${number} \
      --mount source=$name-data,target=/data \
      --mount type=bind,source=$base_dir/software/hadoop/share,target=/share \
      hadoop:$HADOOP_VER /share/start-nodemanager.sh

    ip=$(docker inspect \
      --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' \
      $name)

    sudo sh -c "echo $ip $name.cluster >> /etc/hosts"
  ;;
  start)
    echo "Starting $name"
    docker container start $name
  ;;
  stop)
    echo "Stopping $name"
    docker container kill $name
  ;;
  delete)
    echo "Deleting $name"
    docker container rm $name
    sudo sh -c "sed -i \"/$name.cluster/d\" /etc/hosts"
    docker volume rm $name-data
  ;;
  *)
    print_usage
    exit 1
esac