#!/bin/bash

component=$(basename $0)
base_dir=$(dirname $0)/../..
source $base_dir/cluster/scripts/functions.sh

if [ $# -lt 2 ]; then
  print_component_usage $component
  exit 1
fi

command=$1
number=$2
name=${component}${number}

case "$command" in 
  create)
    case "$3" in
      simple|ha|"")
        cluster_config=${3:-simple}
        
        echo "Creating $name"
    
        docker run -dit \
          --name $name \
          --network=container:namenode${number} \
          --mount type=bind,source=$base_dir/software/hadoop/share,target=/share \
          -m 256M --memory-swap 256M \
          -e "HADOOP_ZKFC_OPTS=-Xmx205m" \
          -e "CLUSTER_CONFIG=$cluster_config" \
          hadoop:$HADOOP_VER bash /share/start-zkfc.sh
        
        addContainerToHostsFile $name
        ;;
      *)
        print_component_usage $component
        exit 1
        ;;
    esac
    ;;
  start)
    echo "Starting $name"
    docker container start $name
    ;; 
  stop)
    echo "Stopping $name"
    docker container kill $name
    ;;
  delete)
    echo "Deleting $name"
    docker container rm $name
    removeLineContaining $name.cluster /etc/hosts
    ;;
  *)
    print_component_usage $component
    exit 1
esac