#!/bin/bash

component=$(basename $0)

function print_usage() {
  echo
  echo "Usage: $component COMMAND NUMBER"
  echo 
  echo "Available commands:"
  echo 
  echo "  create"
  echo "  start"
  echo "  stop"
  echo "  delete"
}

if [ $# -ne 2 ]; then
  print_usage
  exit 1
fi

base_dir=$(dirname $0)/../..
command=$1
number=$2
name=${component}${number}

case "$command" in
  create)
    echo "Creating $name"
    
    # EXPOSED PORTS
    #
    # 2181 - port to listen for client connections
    # 2888 - zookeeper internal communication port
    # 3888 - zookeeper internal communication port 
    #
    # 1st node gets default ports, 2nd node gets ports prefixed by 1 and so on
    
    prefix=$number
    let "prefix -= 1"

    if [ "$prefix" -eq "0" ]; then
      prefix=""
    fi
    
    docker run -dit \
      --name $name \
      --hostname $name.cluster \
      --network=cluster \
      --expose ${prefix}2181 -p ${prefix}2181:${prefix}2181 \
      --expose ${prefix}2888 -p ${prefix}2888:${prefix}2888 \
      --expose ${prefix}3888 -p ${prefix}3888:${prefix}3888 \
      --mount source=$name-data,target=/data \
      --mount type=bind,source=$base_dir/software/zookeeper/share,target=/share \
      zookeeper:$ZOOKEEPER_VER /share/start-zookeeper.sh
    
    ip=$(docker inspect \
      --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' \
      $name)

    sudo sh -c "echo $ip $name.cluster >> /etc/hosts"
  ;;
  start)
    echo "Starting $name"
    docker container start $name
  ;;
  stop)
    echo "Stopping $name"
    docker container kill $name
  ;;
  delete)
    echo "Deleting $name"
    docker container rm $name
    sudo sh -c "sed -i \"/$name.cluster/d\" /etc/hosts"
    docker volume rm $name-data
  ;;
  *)
    print_usage
    exit 1
esac