#!/bin/bash

echo "*** STARTING CLUSTER ***"

echo "STARTING ZOOKEEPER 1"
docker container start zoo1

echo "STARTING ZOOKEEPER 2"
docker container start zoo2

echo "STARTING ZOOKEEPER 3"
docker container start zoo3

echo "STARTING NAMENODE 1"
docker container start nn1

echo "WAITING 10 SECONDS FOR NAMENODE 1 TO START"
sleep 10

echo "STARTING NAMENODE 2"
docker container start nn2

echo "WAITING 10 SECONDS FOR NAMENODE 2 TO START"
sleep 10

echo "STARTING ZKFC 1"
docker container start zkfc1

echo "STARTING ZKFC 2"
docker container start zkfc2

echo "STARTING DATANODE 1"
docker container start w1

echo "STARTING DATANODE 2"
docker container start w2

echo "STARTING DATANODE 3"
docker container start w3