#!/bin/bash

echo "*** STOPPING CLUSTER ***"

echo "STOPPING HREGIONSERVER 3"
docker container kill hrs3

echo "STOPPING HREGIONSERVER 2"
docker container kill hrs2

echo "STOPPING HREGIONSERVER 1"
docker container kill hrs1

echo "STOPPING HMASTER 2"
docker container kill hm2

echo "STOPPING HMASTER 1"
docker container kill hm1

echo "STOPPING MAPREDHISTORYSERVER"
docker container kill mapredh

echo "STOPPING TIMELINESERVER"
docker container kill ts

echo "STOPPING NODEMANAGER 3"
docker container kill nm3

echo "STOPPING NODEMANAGER 2"
docker container kill nm2

echo "STOPPING NODEMANAGER 1"
docker container kill nm1

echo "STOPPING RESOURCEMANAGER 2"
docker container kill rm2

echo "STOPPING RESOURCEMANAGER 1"
docker container kill rm1

echo "STOPPING DATANODE 3"
docker container kill dn3

echo "STOPPING DATANODE 2"
docker container kill dn2

echo "STOPPING DATANODE 1"
docker container kill dn1

echo "STOPPING ZKFC 2"
docker container kill zkfc2

echo "STOPPING ZKFC 1"
docker container kill zkfc1

echo "STOPPING NAMENODE 2"
docker container kill nn2

echo "STOPPING NAMENODE 1"
docker container kill nn1

echo "STOPPING ZOOKEEPER 3"
docker container kill zoo3

echo "STOPPING ZOOKEEPER 2"
docker container kill zoo2

echo "STOPPING ZOOKEEPER 1"
docker container kill zoo1
