#!/bin/bash

echo "*** STARTING CLUSTER ***"

echo "STARTING ZOOKEEPER 1"
docker container start zoo1

echo "STARTING ZOOKEEPER 2"
docker container start zoo2

echo "STARTING ZOOKEEPER 3"
docker container start zoo3

echo "STARTING NAMENODE 1"
docker container start nn1

echo "STARTING NAMENODE 2"
docker container start nn2

echo "STARTING ZKFC 1"
docker container start zkfc1

echo "STARTING ZKFC 2"
docker container start zkfc2

echo "STARTING DATANODE 1"
docker container start dn1

echo "STARTING DATANODE 2"
docker container start dn2

echo "STARTING DATANODE 3"
docker container start dn3

echo "STARTING RESOURCEMANAGER 1"
docker container start rm1

echo "STARTING RESOURCEMANAGER 2"
docker container start rm2

echo "STARTING NODEMANAGER 1"
docker container start nm1

echo "STARTING NODEMANAGER 2"
docker container start nm2

echo "STARTING NODEMANAGER 3"
docker container start nm3

echo "STARTING TIMELINESERVER"
docker container start ts

echo "STARTING MAPREDHISTORYSERVER"
docker container start mapredh