#!/bin/bash

scripts=$(dirname $0)/scripts

echo "*** CREATING CLUSTER ***"

echo "CREATING CLUSTER NETWORK"
docker network create cluster

$scripts/cluster-create-zookeeper.sh 1
$scripts/cluster-create-zookeeper.sh 2
$scripts/cluster-create-zookeeper.sh 3

echo "CREATING EDITS DIR FOR NAMENODES HA"
docker volume create edits

$scripts/cluster-create-namenode.sh 1
echo "WAITING 10 SECONDS FOR NAMENODE 1 TO BOOT UP"
sleep 10
  
$scripts/cluster-create-namenode.sh 2
echo "WAITING 10 SECONDS FOR NAMENODE 2 TO BOOT UP"
sleep 10
  
$scripts/cluster-create-zkfc.sh 1
$scripts/cluster-create-zkfc.sh 2
  
$scripts/cluster-create-datanode.sh 1
$scripts/cluster-create-datanode.sh 2
$scripts/cluster-create-datanode.sh 3

echo "CREATING /tmp/logs ON HDFS TO STORE AGGREGATED LOGS"
hadoop fs -mkdir /tmp
hadoop fs -mkdir /tmp/logs

$scripts/cluster-create-resourcemanager.sh 1
$scripts/cluster-create-resourcemanager.sh 2

$scripts/cluster-create-nodemanager.sh 1
$scripts/cluster-create-nodemanager.sh 2
$scripts/cluster-create-nodemanager.sh 3

$scripts/cluster-create-timelineserver.sh

$scripts/cluster-create-mapredhistoryserver.sh

$scripts/cluster-create-hmaster.sh 1

$scripts/cluster-create-hmaster.sh 2

$scripts/cluster-create-hregionserver.sh 1
$scripts/cluster-create-hregionserver.sh 2
$scripts/cluster-create-hregionserver.sh 3
