#!/bin/bash

echo "*** STOPPING CLUSTER ***"

echo "STOPPING DATANODE 3"
docker container stop w3

echo "STOPPING DATANODE 2"
docker container stop w2

echo "STOPPING DATANODE 1"
docker container stop w1

echo "STOPPING ZKFC 2"
docker container stop zkfc2

echo "STOPPING ZKFC 1"
docker container stop zkfc1

echo "STOPPING NAMENODE 2"
docker container stop nn2

echo "STOPPING NAMENODE 1"
docker container stop nn1

echo "STOPPING ZOOKEEPER 3"
docker container stop zoo3

echo "STOPPING ZOOKEEPER 2"
docker container stop zoo2

echo "STOPPING ZOOKEEPER 1"
docker container stop zoo1
