#!/bin/bash

echo "*** DELETING CLUSTER ***"

echo "DELETING CONTAINERS"
docker container rm hrs3
docker container rm hrs2
docker container rm hrs1
docker container rm hm2
docker container rm hm1
docker container rm mapredh
docker container rm ts
docker container rm nm3
docker container rm nm2
docker container rm nm1
docker container rm rm2
docker container rm rm1
docker container rm dn3
docker container rm dn2
docker container rm dn1
docker container rm zkfc2
docker container rm zkfc1
docker container rm nn2
docker container rm nn1
docker container rm zoo3
docker container rm zoo2
docker container rm zoo1

echo "DELETING VOLUMES"
docker volume rm hrs3-data
docker volume rm hrs2-data
docker volume rm hrs1-data
docker volume rm hm2-data
docker volume rm hm1-data
docker volume rm nm3-data
docker volume rm nm2-data
docker volume rm nm1-data
docker volume rm rm2-data
docker volume rm rm1-data
docker volume rm dn3-data
docker volume rm dn2-data
docker volume rm dn1-data
docker volume rm nn2-data
docker volume rm nn1-data
docker volume rm edits
docker volume rm zoo3-data
docker volume rm zoo2-data
docker volume rm zoo1-data

echo "DELETING CLUSTER NETWORK"
docker network rm cluster